# config/redis.yml

default: &default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  namespace_prefix: lingua_link

development:
  <<: *default

test:
  url: "redis://localhost:6379/0"

production:
  <<: *default
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
